---
- hosts: all
  gather_facts: False

- hosts: appnode
  remote_user: root

  tasks:
    - name: Download Application Repo
      git:
        repo: 'git@bitbucket.org:JakeCallery/cheevos.git'
        accept_hostkey: yes
        dest: /cheevos
        force: true

    - name: Copy Webserver Keys Direcotry
      copy:
       src: /cheevos_keys/
       dest: /cheevos/webserver/keys

    - name: Copy Webserver Certs
      copy:
        src: /cheevos_certs/
        dest: /cheevos/certs

    - name: Install Webpack globally
      npm:
        name: webpack
        global: yes

    - name: Install WebServer Dependencies
      npm:
        path: /cheevos/webserver/src
      retries: 10
      delay: 3

    - name: Install WebClient Dependencies
      npm:
        path: /cheevos/webclient/src
      retries: 10
      delay: 3

...