---
- hosts: all
  gather_facts: False

- hosts: appnode
  remote_user: root

  tasks:
    - name: Download Application Repo
      git:
        repo: 'git@bitbucket.org:JakeCallery/openvote.git'
        accept_hostkey: yes
        dest: /openvote
        force: true

    - name: Copy Webserver Keys Direcotry
      copy:
       src: /openvote/Server/src/keys
       dest: /openvote/Server/src/keys

#    - name: Copy Webserver Certs
#      copy:
#        src: /openvote/certs
#        dest: /openvote/certs

    - name: Install Webpack globally
      npm:
        name: webpack
        global: yes

    - name: Install WebServer Dependencies
      npm:
        path: /openvote/Server/src
      retries: 10
      delay: 3

    - name: Install WebClient Dependencies
      npm:
        path: /openvote/Client/src
      retries: 10
      delay: 3

...