---
- hosts: all
  gather_facts: False

- hosts: appnode
  remote_user: root

  tasks:
    - name: Webpack client app
      script: /cheevos/deployment/appnode/remoteScripts/buildClient.sh

    - name: Remove dist under webserver
      file:
        path: /cheevos/webserver/dist
        state: absent

    - name: Setup dist link
      file:
        src:  /cheevos/webclient/dist
        dest: /cheevos/webserver/views/dist
        state: link