---
- hosts: all
  gather_facts: False

- hosts: appnode
  remote_user: root

  tasks:
    - name: Webpack client app
      script: /openvote/Deployment/appnode/remoteScripts/buildClient.sh

    - name: Remove dist under webserver
      file:
        path: /openvote/Server/dist
        state: absent

    - name: Setup dist link
      file:
        src:  /openvote/dist
        dest: /openvote/Server/src/views/dist
        state: link